# Default params used.
image_size: 64

target: ldm.loss.flowmap_loss.FlowmapLoss

params:
  loss_cfg:
    model:
      use_correspondence_weights: true
      intrinsics:
        name: softmin
        num_procrustes_points: 8192
        min_focal_length: 0.5
        max_focal_length: 2.0
        num_candidates: 60
        regression: null
      extrinsics:
        name: procrustes
        num_points: 1000
        randomize_points: false
      compute_intrinsics: false

    loss:
      flow:
        weight: 10.0
        enable_after: 0
        mapping:
          name: huber
          delta: 0.01

    model_wrapper:
      patch_size: 32 #a modifier?

    cropping:
      image_shape:
        - ${data.image_size}
        - ${data.image_size}
      flow_scale_multiplier: 4
      patch_size: 32 #a modifier?