# Default params used.
n_future: 1
channels_m: 3

modalities_in:
  - target: ldm.misc.modalities.Modality
    params:
      name: trgt
      modality: rgb
      multiplicity: ${n_future}
      channels_m: ${channels_m} 
      denoised: True

  - target: ldm.misc.modalities.Modality
    params:
      name: optical_flow
      modality: flow
      multiplicity: ${n_future}
      channels_m: ${channels_m} 
      denoised: True

modalities_out:
  - target: ldm.misc.modalities.Modality
    params:
      name: trgt
      modality: rgb
      multiplicity: ${n_future}
      channels_m: ${channels_m} 
      denoised: True

  - target: ldm.misc.modalities.Modality
    params:
      name: optical_flow
      modality: flow
      multiplicity: ${n_future}
      channels_m: ${channels_m} 
      denoised: True

  - target: ldm.misc.modalities.Modality
    params:
      name: depth_ctxt
      modality: depth
      multiplicity: 1
      channels_m: ${channels_m} 
      denoised: False

  - target: ldm.misc.modalities.Modality
    params:
      name: depth_trgt
      modality: depth
      multiplicity: ${n_future}
      channels_m: ${channels_m} 
      denoised: False
  
  
  
  