target: ldm.lr_scheduler.LambdaLinearScheduler
base_learning_rate: 1.0e-04
params:
  warm_up_steps: [0, 2000] # constant then linear decrease during 2000 steps
  cycle_lengths: [5000, 10000000000000 ] # constant during 5000 steps
  f_start: [1.0, 1.0 ]
  f_max: [ 1., 0.1 ]
  f_min: [ 1., 0.1 ]