target: ldm.lr_scheduler.LambdaLinearScheduler
params:
  warm_up_steps: [0, 0]
  cycle_lengths: [3000, 10000000000000] # incredibly large number to prevent corner cases
  f_start: [1.e-6, 1.e-6]
  f_max: [1., 0.1]
  f_min: [1., 0.1]