data:
  name: co3d
  root: datasets/CO3Dv2
  image_folder: images
  categories: 
    - hydrant
  scenes: null
  image_shape: null
  stride: 1

raft:
  model: models/preprocessing/flow/raft/raft-sintel.pth
  warm_start: True
  iters: 32
  small: False
  mixed_precision: False
  alternate_corr: False