target: ldm.modules.diffusionmodules.openaimodel.UNetModel

# Normally unused here.
image_size: 64

params:
  image_size: ${image_size} # unused
  model_channels: 320 #number of intermediate layer channels across the U-Net
  attention_resolutions: [4, 2, 1]
  num_res_blocks: 2
  channel_mult: [1, 2, 4, 4]
  num_heads: 8
  # use_spatial_transformer: True
  # transformer_depth: 1
  # context_dim: 768  #dim of crossattn conditioning
  use_checkpoint: True
  legacy: False